[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "telegram-bot"
version = "1.0.0"
description = "Advent calendar Telegram bot"
requires-python = ">=3.11"
dependencies = [
    "python-telegram-bot",
]